export const NUM_VIDS_TO_FETCH = 24;
export const NUM_COMMENTS_TO_FETCH = 15;
export const NUM_RELATED_VIDS_TO_FETCH = 20;
export const NUM_SEARCH_RESULTS_TO_FETCH = 40;
export const NUM_SUBSCRIPTIONS_TO_FETCH = 50;
